name: 3 Principles Resources
favicon: null
layout_spectrum: 0.904966723639518
typography_spectrum: 0.4358160679694265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8360952290240675
  lightness: 0.8241775839123875
  saturation: 0.06874049664475024
  rhythmicContrast: 0.3490728405304253
purpose: []
